version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: employee-directory-postgres-password
    ports:
      - 5432:5432

  backend:
    image: employee-directory-backend
    command: npx nodemon -r esm --inspect=0.0.0.0:5858 --trace-warnings src/server.js
    environment:
      PGHOST: host.docker.internal
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: employee-directory-postgres-password
    ports:
      - 4000:4000
      - 5858:5858 # debug port
    # Uncomment these for dev live reloading
    # volumes:
    #   - ./backend:/usr/src/app

  frontend:
    image: employee-directory-frontend
    command: npx snowpack dev
    ports:
      - 8181:8181
    # Uncomment these for dev live reloading
    # volumes:
    #   - ./frontend:/usr/src/app
