version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: employee-directory-postgres-password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    image: bgoosman/employee-directory-backend
    command: npx nodemon -r esm --trace-warnings src/server.js
    environment:
      PGHOST: host.docker.internal
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: employee-directory-postgres-password
    ports:
      - 4000:4000
    volumes:
      - ./backend:/usr/src/app
